name: app_postsalud
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-334.3.beta


dependencies:
  flutter:
    sdk: flutter
  
  flutter_map: ^8.1.1
  geolocator: ^10.1.0

  latlong2: ^0.9.1
  carousel_slider: ^5.0.0
  mysql_client: ^0.0.27
  image_picker: ^1.1.2
  google_maps_flutter: ^2.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/

